### ---- Posttest 7 Tensorflow ----
### Sherina Laraswati
### 2109106050
### Informatika A 2021

In [32]:
import tensorflow as tf

## Tensor dengan shape (5,5) dengan nilai random yang disimpan di dalam variable random tensor

In [33]:
random_tensor = tf.random.normal([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.1000824 ,  1.3291217 , -0.52346504, -0.43433666, -1.9020158 ],
       [ 0.0082488 ,  0.9488962 ,  0.93592894, -0.66424435, -0.29272172],
       [ 0.3519842 , -1.8289    ,  0.1154035 , -0.8119289 , -1.1299595 ],
       [-0.76826435, -0.10811629, -0.99425375, -1.3926783 ,  0.39757574],
       [-0.9746144 , -0.7996424 , -0.26467425,  1.2341244 ,  0.91120714]],
      dtype=float32)>

## Tensor dengan shape (5,5) dari sebuah list dengan nilai bil prima dalam var bilangan prime_tensor

In [34]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 
                           23, 29, 31, 37, 41, 43, 47,
                           53, 59, 61, 67, 71, 73, 79,
                           83, 89, 97], shape = [5, 5], dtype = tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## Menampilkan dimensi dari kedua variable

In [35]:
## Menampilkan dimensi variable random_tensor dengan menggunakan Dimension Expansion

dimensi_random_tensor = tf.random.normal([5, 5])
dimensi_random_tensor.shape

TensorShape([5, 5])

In [36]:
tf.expand_dims(dimensi_random_tensor,axis=0).shape

TensorShape([1, 5, 5])

In [37]:
## Menampilkan dimensi variable prime_tensor dengan menggunakan Dimension Display

dimensi_prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 
                           23, 29, 31, 37, 41, 43, 47,
                           53, 59, 61, 67, 71, 73, 79,
                           83, 89, 97], shape = [5, 5])
dimensi_prime_tensor.shape

TensorShape([5, 5])

In [38]:
tf.shape(dimensi_prime_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

## perhitungan aritmatika 2 variable


In [39]:
## Pertambahan

a = random_tensor
b = prime_tensor

tf.add(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.8999176,  4.3291216,  4.476535 ,  6.5656633,  9.097984 ],
       [13.008248 , 17.948896 , 19.935928 , 22.335756 , 28.70728  ],
       [31.351984 , 35.1711   , 41.115402 , 42.188072 , 45.87004  ],
       [52.231735 , 58.891884 , 60.005745 , 65.60732  , 71.397575 ],
       [72.02538  , 78.200356 , 82.73533  , 90.23412  , 97.91121  ]],
      dtype=float32)>

In [40]:
## Pengurangan

a = random_tensor
b = prime_tensor

tf.subtract(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -3.1000824,  -1.6708783,  -5.523465 ,  -7.4343367, -12.902016 ],
       [-12.991752 , -16.051104 , -18.064072 , -23.664244 , -29.29272  ],
       [-30.648016 , -38.8289   , -40.884598 , -43.811928 , -48.12996  ],
       [-53.768265 , -59.108116 , -61.994255 , -68.39268  , -70.602425 ],
       [-73.97462  , -79.799644 , -83.26467  , -87.76588  , -96.08879  ]],
      dtype=float32)>

In [41]:
## Perkalian

a = random_tensor
b = prime_tensor

tf.matmul(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-163.01599  , -175.9585   , -186.07101  , -198.01973  ,
        -213.49268  ],
       [ -15.20769  ,  -11.53008  ,   -8.37145  ,   -8.429306 ,
          -3.9579697],
       [-145.01349  , -162.93602  , -171.57193  , -189.6041   ,
        -210.99533  ],
       [ -78.552826 ,  -91.68969  ,  -98.614525 , -108.54264  ,
        -118.631516 ],
       [ 111.377235 ,  118.488    ,  119.993866 ,  127.188705 ,
         129.65985  ]], dtype=float32)>

In [42]:
## Pembagian

a = random_tensor
b = prime_tensor

tf.divide(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.5500412 ,  0.44304058, -0.10469301, -0.0620481 , -0.17291053],
       [ 0.00063452,  0.05581743,  0.04925942, -0.02888019, -0.01009385],
       [ 0.01135433, -0.04942973,  0.00281472, -0.01888207, -0.02404169],
       [-0.01449555, -0.00183248, -0.01629924, -0.02078624,  0.00559966],
       [-0.01335088, -0.01012206, -0.00318885,  0.01386657,  0.00939389]],
      dtype=float32)>

In [43]:
## Perpangkatan

a = random_tensor
b = prime_tensor

tf.pow(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.2101812e+00,  2.3479793e+00, -3.9304148e-02, -2.9159859e-03,
        -1.1785698e+03],
       [ 8.1861623e-28,  4.0993807e-01,  2.8419384e-01, -8.1948507e-05,
        -3.3666148e-16],
       [ 8.7542380e-15, -5.0237537e+09,  0.0000000e+00, -1.2860997e-04,
        -3.1185635e+02],
       [-8.5519702e-07, -0.0000000e+00, -7.0360941e-01, -4.3451361e+09,
         3.6208530e-29],
       [-1.5303668e-01, -2.1319087e-08, -0.0000000e+00,  1.3519053e+08,
         1.2102081e-04]], dtype=float32)>

## Maksimal dan minimal var random_tensor

In [44]:
argmax = random_tensor
maksimal = tf.argmax(argmax, axis = 0) # Nilai max perkolom
maksimal

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 1, 4, 4], dtype=int64)>

In [45]:
maksimal = tf.argmax(argmax, axis=1) # Nilai max perbaris
maksimal

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 1, 0, 4, 3], dtype=int64)>

In [46]:
argmin = random_tensor
minimal = tf.argmin(argmin, axis = 0) # Nilai min perkolom
minimal

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 2, 3, 3, 0], dtype=int64)>

In [47]:
mainimal = tf.argmax(argmax, axis=1) # Nilai min perbaris
minimal

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 2, 3, 3, 0], dtype=int64)>

## Penggabungan var random_tensor dengan prime_tensor (Concatenation)

In [48]:
concat_1 = random_tensor
concat_2 = prime_tensor

In [49]:
concat_1_2 = tf.concat([concat_1, concat_2], axis = 0)
concat_1_2

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-1.10008240e+00,  1.32912171e+00, -5.23465037e-01,
        -4.34336662e-01, -1.90201581e+00],
       [ 8.24880041e-03,  9.48896229e-01,  9.35928941e-01,
        -6.64244354e-01, -2.92721719e-01],
       [ 3.51984203e-01, -1.82889998e+00,  1.15403496e-01,
        -8.11928928e-01, -1.12995946e+00],
       [-7.68264353e-01, -1.08116291e-01, -9.94253755e-01,
        -1.39267826e+00,  3.97575736e-01],
       [-9.74614382e-01, -7.99642384e-01, -2.64674246e-01,
         1.23412442e+00,  9.11207139e-01],
       [ 2.00000000e+00,  3.00000000e+00,  5.00000000e+00,
         7.00000000e+00,  1.10000000e+01],
       [ 1.30000000e+01,  1.70000000e+01,  1.90000000e+01,
         2.30000000e+01,  2.90000000e+01],
       [ 3.10000000e+01,  3.70000000e+01,  4.10000000e+01,
         4.30000000e+01,  4.70000000e+01],
       [ 5.30000000e+01,  5.90000000e+01,  6.10000000e+01,
         6.70000000e+01,  7.10000000e+01],
       [ 7.30000000e+01,  7.90000

## Sorting dari kedua variable diatas (descending)

In [50]:
sorting_1 = random_tensor
sorting_2= prime_tensor

In [51]:
sorting_desc = tf.sort([sorting_1, sorting_2], direction="DESCENDING")
sorting_desc

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[ 1.32912171e+00, -4.34336662e-01, -5.23465037e-01,
         -1.10008240e+00, -1.90201581e+00],
        [ 9.48896229e-01,  9.35928941e-01,  8.24880041e-03,
         -2.92721719e-01, -6.64244354e-01],
        [ 3.51984203e-01,  1.15403496e-01, -8.11928928e-01,
         -1.12995946e+00, -1.82889998e+00],
        [ 3.97575736e-01, -1.08116291e-01, -7.68264353e-01,
         -9.94253755e-01, -1.39267826e+00],
        [ 1.23412442e+00,  9.11207139e-01, -2.64674246e-01,
         -7.99642384e-01, -9.74614382e-01]],

       [[ 1.10000000e+01,  7.00000000e+00,  5.00000000e+00,
          3.00000000e+00,  2.00000000e+00],
        [ 2.90000000e+01,  2.30000000e+01,  1.90000000e+01,
          1.70000000e+01,  1.30000000e+01],
        [ 4.70000000e+01,  4.30000000e+01,  4.10000000e+01,
          3.70000000e+01,  3.10000000e+01],
        [ 7.10000000e+01,  6.70000000e+01,  6.10000000e+01,
          5.90000000e+01,  5.30000000e+01],
        [ 9